mysite/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.conf.urls import url, include
from django.contrib import admin
from Issue.views import index, add_issue, edit_issue, del_issue, notfound, issue_list

urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'^$', auth_views.login, { 'authentication_form':AuthenticationForm } ,name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^index$',index, name ='home'),
    url(r'^list/(\w+)$',issue_list),
    url(r'^notfound/',notfound),
    url(r'^issue/add$',add_issue),
    url(r'^issue/edit/(\d+)$',edit_issue),
    url(r'^issue/del/(\d+)$',del_issue), 
    ]

Issue/models.py
# _*_ coding:utf-8 _*_

from __future__ import unicode_literals

from datetime import datetime, date
from django.db import models
from django import forms
from functools import partial
from django.forms import ModelForm, Textarea
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Issue(models.Model):
   
    no = models.AutoField(primary_key=True)
    topic = models.CharField(blank=True,max_length=20)
    desc = models.TextField(blank=True,max_length=255)
    notes = models.TextField(blank=True,max_length=255)
    type = models.CharField(blank=True,max_length=10)
    owner = models.CharField(blank=True,max_length=20)
    start_date = models.CharField(blank=True,max_length=10)
    end_date = models.CharField(blank=True,max_length=10)
    close_date = models.CharField(blank=True,max_length=10)
    status = models.CharField(blank=True,max_length=20)
    sys_time = models.DateTimeField(blank=True,default=datetime.now, editable = False)

    def __unicode__(self):
        return self.topic

class IssueForm(ModelForm):
    STATUS = [
        ['New','New'],
        ['Processing','Processing'],
        ['Rejected','Rejected'],
        ['Closed','Closed'],
    ]
    
    status = forms.ChoiceField(label='Status', choices=STATUS)

    class Meta:
        model = Issue
        fields = '__all__'
        labels = {
                'no': _('No'),
                'topic': _('Topic'),
                'desc': _('Description'),
                'notes': _('Notes'),
                'type': _('Type'),
                'owner': _('Owner'),
                'start_date': _('Start Date'),
                'end_date': _('End Date'),
                'close_date': _('Close Date'),
                'status': _('Status'),
                'sys_time':_('System Time'),
        }
        widgets = {
                'desc': Textarea(attrs={'cols': 50, 'rows': 5}),
                'notes': Textarea(attrs={'cols': 50, 'rows': 5}),
                'start_date': forms.DateInput(attrs={'class':'datepicker'}),
        }

mysite/forms.py
# _*_ coding: utf-8 _*_
from django import forms

class ContactForm(forms.Form):
    CITY = [
        ['TP','Taipei'],
        ['TY','Taoyuang'],
        ['TC','Taichung'],
        ['TN','Tainan'],
        ['KS','Kaohsiung'],
        ['NA','Others'],
    ]

    user_name = forms.CharField(label='您的姓名', max_length = 50, initial= '李大仁')
    user_city = forms.ChoiceField(label='居住城市', choices = CITY)
    user_school = forms.BooleanField(label='是否在學', required = False)
    user_email = forms.EmailField(label='電子郵件')
    user_message = forms.CharField(label='您的意見', widget = forms.Textarea)

Issue/views.py
# _*_ coding: utf-8 _*_

from django.shortcuts import render, redirect
from django.template import RequestContext
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from django.db.models import Max
from Issue.models import Issue, IssueForm
from django.core.mail import EmailMessage

# Create your views here.
def index(request):
    template = get_template('index.html')
    now = datetime.now
    html = template.render(locals())
    return HttpResponse(html)

def issue_list(request, criteria ):
    template = get_template('issue_list.html')
    if criteria == 'all':
        all = Issue.objects.all()
    else:
        all = Issue.objects.filter(status = criteria)
    now = datetime.now
    html = template.render(locals())
    return HttpResponse(html)

def add_issue(request):
    all = Issue.objects.all()
    max_no = all.aggregate(Max('no'))
    if max_no['no__max'] == None:
        new_no = 1
    else:
        new_no = max_no['no__max'] + 1
    
    if request.method == 'POST':
        issue_form = IssueForm(request.POST)
        if issue_form.is_valid():
            msg = "您的案件已儲存！"
            new_issue = issue_form.save(commit=False)
            new_issue.no = new_no
            new_issue.save()
            return HttpResponseRedirect('/list/all')
        else:
            msg = "欄位驗證錯誤！"
    else:
        issue_form = IssueForm()
        new_issue = issue_form.save(commit=False)
        new_issue.no = new_no
    template = get_template('issue_editor.html')
    request_context = RequestContext(request)
    request_context.push(locals())
    html = template.render(request_context)
    return HttpResponse(html)

def edit_issue(request,issue_no):
    old_issue = Issue.objects.get(no = issue_no)
    if request.method == 'POST':
        issue_form = IssueForm(request.POST, instance = old_issue)
        if issue_form.is_valid():
            msg = "您的案件已儲存！"
            new_issue = issue_form.save()
            return HttpResponseRedirect('/list/all')
        else:
            msg = "欄位驗證錯誤！"
    else:
        issue_form = IssueForm(instance = old_issue)
        new_issue = issue_form.save(commit=False)
    template = get_template('issue_editor.html')
    request_context = RequestContext(request)
    request_context.push(locals())
    html = template.render(request_context)
    return HttpResponse(html)

def del_issue(request, issue_no):
    old_issue = Issue.objects.get(no = issue_no)
    old_issue.delete()
    return HttpResponseRedirect('/list/all')

def notfound(request, issue_no):
    template = get_template('notfound.html')
    now = datetime.now
    html = template.render(locals())
    return HttpResponse(html)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>RMS 專案管理系統</title>
        <link rel="stylesheet" type="text/css" href="/static/css/style1.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </head>
    <body>
        <header>
            <table>
                <tr>
                    <td><a href='/index'><img src='{% static "images/logo.jpeg" %}' width = 150 /></a></td>
                    <td><h1>RMS-Requirement Management System<h1</td>
                </tr>
            </table>
        </header>
        <ul>
            <li><a href="/index">Home</a></li>
            <li><a class="active" href="/list/all">All</a></li>
            <li><a href="/list/New">New</a></li>
            <li><a href="/list/Processing">Processing</a></li>
            <li><a href="/list/Rejeted">Rejected</a></li>
            <li><a href="/list/Closed">Closed</a></li>
        </ul>
        </br>
        {% block main %}{% endblock %}
        </br>
        <ul>
            <li><a href="/admin">Admin</a></li>
            <li><a href="/logout">Logout</a></li>
        </ul>
        </br>
        This is a django website, made by Alan Huang, 2017
    </body>
</html>

templates/contact.html
<!DOCTYPE html>
<html>
<head!>
<title>聯絡我們</title>
</head>
<body>
<h2>Email 聯絡我們</h2>
{% if message %}
    <div class='alert alert-warning'>{{message}}</div>
    {{user_name}}<br/>
    {{user_city}}<br/>
    {{user_school}}<br/>
    {{user_email}}<br/>
    {{user_message | linebreaks}}<br/>
{% endif %}

  <form name='frm_email' action='' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">送出</button>
  </form>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block main %}
<p>RMS system is developed by Python3 with django, deployed on heroku server.</p>
<p>The listed functionals below are supported：<br>
<ol>
    <li>You can press <font color="red">[All]</font> to view all issues.</li>
    </br>
    <li>You can press <font color="red">[create issue] [edit] [delete]</font> to edit issues.</li>
    </br>
    <li>You can press <font color="red">[Admin]</font> to manipulate advanced settings.</li>
    </br>
</ol>
{%endblock%}

templates/issue_editor.html
{% extends 'base.html' %}
{% block main %}
<h4>Issue No: {{new_issue.no}}</h4>
<form name='frm_issue_edit' action='' method='POST'>
    {% csrf_token %}
    <table id = "tb_issue_editor">
        {{issue_form.as_table}}
    </table>
    <script>
        $( function() {
            $( "#id_start_date" ).datepicker({dateFormat: 'yy-mm-dd'});
            $( "#id_end_date" ).datepicker({dateFormat: 'yy-mm-dd'});
            $( "#id_close_date" ).datepicker({dateFormat: 'yy-mm-dd'});
        });
    </script>

<!--
主題: <input type="text" name="topic" value={{new_issue.topic}}>&emsp;
負責人: <input type="text" name="owner" value={{new_issue.owner}}>&emsp;
類型: <input type="text" name="type" value={{new_issue.type}}>&emsp;
<br/><br/>
起始日: <input type="text" name="start_date" value={{new_issue.start_date}}>&emsp;
到期日: <input type="text" name="end_date" value={{new_issue.end_date}}>&emsp;
結案日: <input type="text" name="close_date" value={{new_issue.close_date}}>&emsp;
<br/><br/>
狀態: <input type="text" name="status" value={{new_issue.status}}>&emsp;
<br><br>
問題描述:<br/><br/>
<textarea rows="5" cols="100">
{{new_issue.desc}}
</textarea>
<br><br>

備註:<br/><br/>
<textarea rows="5" cols="100">
{{new_issue.notes}}
</textarea>
<br><br>
-->

<input type="submit" value="OK">
<input type="reset" value="Clear">
</form>
{% endblock %}

templates/issue_list.html
{% extends 'base.html' %}
{% block main %}
<table  id="tbl_issue" width=100% rules="all" cellpadding='5';>
    <tr>
        <th>No</th><th>Topic</th><th>Description</th><th>Notes</th> <th>Owner</th>
        <th>Type</th><th>Start Date</th><th>End Date</th><th>Close Date</th><th>Status</th>
        <th colspan="2"><center>[<a href='/issue/add'>create issue</a>]</center></th>
    </tr>
    {% for issue in all %}
        <tr>
            <td id='td_no'><center>{{issue.no}}</center></td>
            <td id='td_topic'>{{issue.topic}}</td>
            <td id='td_desc'>{{issue.desc}}</td>
            <td id='td_notes'>{{issue.notes}}</td>
            <td id='td_owner'>{{issue.owner}}</td>
            <td id='td_type'>{{issue.type}}</td>
            <td id='td_start_date'>{{issue.start_date}}</td>
            <td id='td_end_date'>{{issue.end_date}}</td>
            <td id='td_close_date'>{{issue.close_date}}</td>
            <td id='td_status'>{{issue.status}}</td>
            <td id='td_edit'>[<a href='/issue/edit/{{issue.no}}'>edit</a>]</td>
            <td id='td_del'>[<a href='/issue/del/{{issue.no}}'>delete</a>]</td>
            </td>
        </tr>
    {% empty %}
        <p>There is no issue available!</p>
    {% endfor %}
    <script>
        $( function() {
            $("#tbl_issue").attr('style',"border:3px #FFAC55 double;padding:5px;background-color:#FFFFBB");
            $("th").attr('style',"border:3px #FFAC55 double;padding:5px;");
            $("#td_no").attr('width', 10);
            $("#td_topic").attr('width', 60);
            $("#td_desc").attr('width', 200);
            $("#td_notes").attr('width', 200); 
            $("#td_owner").attr('width', 60);
            $("#td_type").attr('width', 60);
            $("#td_start_date").attr('width', 90);
            $("#td_end_date").attr('width', 90);
            $("#td_close_date").attr('width', 90);
            $("#td_status").attr('width', 60);
            $("#td_edit").attr('width', 20);
            $("#td_del").attr('width', 20);
        } );
    </script>

</table>
{%endblock%}

templates/notfound.html
{% extends 'base.html' %}
{% block message %}無法顯示網頁{%endblock%}
{% block main %}
<h3>
    編輯失敗, 案件編號: {{issue_no}}<br>
    無法顯示頁面, 請前往
    <a href='/'>HOME</a>
</h3>
{%endblock%}